### ISSUE TITLE
Add gulp-autoprefixer to our Gulp styles pipeline and remove _prefix() sass mixin

### ISSUE THREAD

**Issue by Smona** [politicalrev/political-revolution.com#13]
[gulp-autoprefixer](https://www.npmjs.com/package/gulp-autoprefixer) transparently prefixes the outputted css for maximum browser compatibility. The forty theme used a custom mixin that we no longer want to support.

- [x] Add gulp-autoprefixer to our gulpfile style task
- [x] Remove all instances of the forty theme prefix mixin

**Comment by NathanAB** [comment]
Unless I'm missing something, this already seems to be the case: https://github.com/politicalrev/political-revolution.com/blob/master/web/app/themes/thepoliticalsage/gulpfile.js#L102

**Comment by Smona** [comment]
Oh, neat! Don't know how I missed that 😂

**Comment by Smona** [comment]
Completed in 091e05e
