### ISSUE TITLE
The homepage "main banner" gap issue due to conflict here.

### ISSUE THREAD

**Issue by innovativedmm** [politicalrev/political-revolution.com#21]
banner.scss
                       @include breakpoint(small) {
			**_@include padding(3em, 0, (2em, 0, 0, 0));_**
			**_height: 80vh;_**
			margin-bottom: -2.75em;
			max-height: none;
			**_min-height: 20em;_**
			**_top: -2.75em;_**
			background-size: 180%;
			background-position: 50% calc(-80px + 10vw);
			background-attachment: scroll;

@media screen and (max-width: 736px)
#banner.major {
    height: 100vw;
    min-height: 31em;
    max-height: none;

**Comment by Smona** [comment]
Let's just focus on implementing the new homepage rather than fixing the old
