### ISSUE TITLE
Evaluate Form Plugins

### ISSUE THREAD

**Issue by leggomuhgreggo** [politicalrev/political-revolution.com#33]
## Overview
Right now forms are hardcoded and processed through a couple third party APIs (eg google, tinyletter, etc). In the interest to reducing friction to form building for site maintainers, we wanted to explore options for WP form plugins.

[Here's](https://premium.wpmudev.org/blog/10-top-quality-plugins-for-creating-custom-wordpress-forms/) a "Top Ten" list of WP form plugins. I've used the first half on the list, but only very superficially. The rest I don't recognize, and also look less polished from the very shallow once over I gave--I suspect they could have kept it top 5, honestly.

**If anyone has any experience, I'd love to hear your thoughts!**

## Evaluation Rubric/Reqs 
1. **Data Processing** - What kind of customizations exist? Reports, action sequence triggers, etc
2. **Cost** - I'm 99% sure we can operate at the free tier. 
3. **Style Considerations** - It'd be cool to leverage Bootstrap form styles, but I'd say feature set is more important. Easy enough to bake form styles.
4. **Front End Inclusion Flexibility** - shortcode? widget assignment? etc
5. **Data integration** - Is there an easy way to consolidate existing form data, from like a google sheet?

Many thanks!

**Comment by innovativedmm** [comment]
@Smona Do you think this is the contact plugin we need? If so, let's go for it.

**Comment by innovativedmm** [comment]
I'm stoodpid.

**Comment by Smona** [comment]
I'm going to install ninja forms and you can see if it works for what you want @innovativedmm

**Comment by Smona** [comment]
Ninja Forms is incorrectly exporting survey data. @innovativedmm do we need to try a different plugin? Didi you contact plugin support?
