### ISSUE TITLE
Feature: Use CI to automatically run `cap staging deploy` on every commit to master

### ISSUE THREAD

**Issue by Smona** [politicalrev/political-revolution.com#7]
Since our build script is already configured this should be pretty simple. We can use Travis CI or similar

**Comment by innovativedmm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Using bootstrap 4 and scss!](https://trello.com/c/ae5ClDR7/193-using-bootstrap-4-and-scss)

**Comment by Smona** [comment]
We should also run our build steps as a check for pull requests (possibly commits to master too)

**Comment by Smona** [comment]
Implemented!
